In [3]:
file1 = "/Users/ayadav/Downloads/164410_790308_bundle_archive/test.csv"

In [4]:
df_test = pd.read_csv(file1)

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy.stats import norm
from scipy.stats import t
from numpy.random import seed

In [6]:
from pycaret.datasets import get_data

In [7]:
dataset= pd.read_csv('/Users/ayadav/Downloads/loan_train.csv')

In [8]:
dataset.head()

,EMPLOYMENT_TYPE,MOBILENO_AVL_FLAG,AADHAR_FLAG,PAN_FLAG,VOTERID_FLAG,DRIVING_FLAG,PASSPORT_FLAG,PERFORM_CNS_SCORE,PERFORM_CNS_SCORE_DESCRIPTION,PRI_ACTIVE_ACCTS,...,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,LOAN_DEFAULT,DISBURSED_AMOUNT_new,ASSET_COST,LTV_new,DISBURSAL_DATE
0,Salaried,1,1,0,0,0,0,0,No Bureau History Available,0,...,0,0,0,0,0,0,50578.0,58400,54356.993528,03-08-2018
1,Self employed,1,1,0,0,0,0,598,I-Medium Risk,1,...,1991,0,1,23,0,1,47145.0,65550,54356.993528,26-09-2018
2,Self employed,1,1,0,0,0,0,0,No Bureau History Available,0,...,0,0,0,0,0,0,53278.0,61360,54356.993528,01-08-2018
3,Self employed,1,1,0,0,0,0,305,L-Very High Risk,0,...,31,0,0,15,1,1,57513.0,66113,54356.993528,26-10-2018
4,Self employed,1,1,0,0,0,0,0,No Bureau History Available,0,...,0,0,0,0,1,1,52378.0,60300,54356.993528,26-09-2018

In [9]:
data = dataset.sample(frac=0.95, random_state=786)
data_unseen = dataset.drop(data.index)
data.reset_index(inplace=True, drop=True)
data_unseen.reset_index(inplace=True, drop=True)
print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (221496, 25)
Unseen Data For Predictions: (11658, 25)

In [10]:
from pycaret.datasets import get_data
#dataset = get_data('df_train')

In [11]:
from pycaret.classification import *
exp_name = setup(data = data,  target = 'LOAN_DEFAULT',session_id=123,fix_imbalance = True)

Setup Succesfully Completed!

In [ ]:
best_model = compare_models()

IntProgress(value=0, description='Processing: ', max=176)

Initiated  . . . . . . . . . . . . . . . . . .                   00:13:09
Status     . . . . . . . . . . . . . . . . . .       Fitting Fold 5 of 10
Estimator  . . . . . . . . . . . . . . . . . .  Extreme Gradient Boosting
ETC        . . . . . . . . . . . . . . . . . .     6.94 Minutes Remaining

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
0,Gradient Boosting Classifier,0.7827,0.6235,0.0002,0.2333,0.0004,0.0002,0.0034,45.7848
1,Ada Boost Classifier,0.7808,0.5798,0.0089,0.3047,0.0170,0.0061,0.0198,11.8673
2,Random Forest Classifier,0.7497,0.5509,0.0992,0.2831,0.1469,0.0385,0.0458,0.8037
3,Extra Trees Classifier,0.7393,0.5553,0.1263,0.2792,0.1739,0.0446,0.0496,9.9205
4,Decision Tree Classifier,0.6622,0.5188,0.2648,0.2443,0.2541,0.0363,0.0363,1.7479
5,Ridge Classifier,0.5697,0.0000,0.6068,0.2766,0.3800,0.1161,0.1372,0.3447
6,K Neighbors Classifier,0.5695,0.5328,0.4433,0.2374,0.3092,0.0364,0.0402,32.6910
7,Linear Discriminant Analysis,0.5695,0.6185,0.6066,0.2764,0.3798,0.1158,0.1369,1.7209
8,Logistic Regression,0.5331,0.5817,0.6136,0.2583,0.3635,0.0831,0.1026,2.1177
9,SVM - Linear Kernel,0.4934,0.0000,0.5386,0.2197,0.3036,0.0091,0.0162,1.0912
10,Naive Bayes,0.4590,0.5742,0.6651,0.2458,0.3254,0.0441,0.0701,0.2391
11,Quadratic Discriminant Analysis,0.2256,0.5135,0.9909,0.2180,0.3574,0.0018,0.0133,0.9874

In [16]:
#top3 = compare_models(n_select = 3)

## CatBoost Classifier

In [13]:
gbc = create_model('gbc')

In [17]:
print(gbc)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [15]:
tuned_gbc = tune_model(gbc)

## Feature Importance Plot

In [1]:
plot_model(tuned_gbc, plot = 'auc')

NameError: name 'plot_model' is not defined

## Predict model

In [18]:
predict_model(tuned_catboost);

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC
0,CatBoost Classifier,0.7829,0.6364,0.0026,0.5909,0.0051,0.0032,0.0279

## Finalize model for deployment

In [19]:
final_catboost = finalize_model(tuned_catboost)

In [20]:
print(final_catboost)

<catboost.core.CatBoostClassifier object at 0x7fe9d1be8a90>

## Predict on unseen data

In [34]:
unseen_predictions1 = predict_model(final_catboost, data=data_unseen)
unseen_predictions1.head()

,UNIQUEID,DISBURSED_AMOUNT,LTV,BRANCH_ID,SUPPLIER_ID,MANUFACTURER_ID,CURRENT_PINCODE_ID,STATE_ID,EMPLOYEE_CODE_ID,MOBILENO_AVL_FLAG,...,SEC_OVERDUE_ACCTS,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,NO_OF_INQUIRIES,LOAN_DEFAULT,Label,Score
0,508030,49458,82.54,78,17014,45,2095,4,1646,1,...,0,0,0,0,0,0,0,0,0,0.2477
1,573625,54273,80.73,78,17014,45,2102,4,1646,1,...,0,0,0,0,0,0,0,0,0,0.2677
2,603152,49713,82.95,78,17014,45,2070,4,1646,1,...,0,0,2884,0,0,0,0,0,0,0.1721
3,501429,49349,76.49,34,15196,86,978,6,1863,1,...,0,0,2785,0,1,0,0,0,0,0.0945
4,445234,53578,79.13,34,15196,86,992,6,1863,1,...,0,0,0,0,0,0,0,0,0,0.1938

In [40]:
unseen_predictions2 = predict_model(final_catboost, data=df_test)
unseen_predictions2.head()

,UNIQUEID,DISBURSED_AMOUNT,ASSET_COST,LTV,BRANCH_ID,SUPPLIER_ID,MANUFACTURER_ID,CURRENT_PINCODE_ID,DATE_OF_BIRTH,EMPLOYMENT_TYPE,...,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,Label,Score
0,655269,53478,63558,86.54,67,22807,45,1497,01-01-1974,Salaried,...,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,0.3728
1,723482,55513,63163,89.45,67,22807,45,1497,20-05-1985,Self employed,...,0,5605,0,1,0,0yrs 8mon,1yrs 0mon,1,0,0.3389
2,758529,65282,84320,79.93,78,23135,86,2071,14-10-1995,Salaried,...,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,0.3573
3,763449,46905,63896,76.58,78,17014,45,2070,01-06-1973,Self employed,...,0,0,0,0,0,2yrs 5mon,2yrs 5mon,0,0,0.3128
4,708663,51428,63896,86.08,78,17014,45,2069,01-06-1972,Salaried,...,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,0.4132

In [42]:
from pycaret.utils import check_metric
check_metric(unseen_predictions['LOAN_DEFAULT'],unseen_predictions['Label'], metric = 'Score')

UnboundLocalError: local variable 'result' referenced before assignment

## Save the model

In [25]:
save_model(final_rf,'Final RF Model 15DEC2020')

Transformation Pipeline and Model Succesfully Saved

In [ ]:
/Users/ayadav/capstone with pycaret.ipynb